=== borjamiguens/DAWlenguajeDeMarcas/Evaluacion_1/Practicas/XML_XSD_actividades/plantillaClave/plantillaClave.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Plantilla para implementar claves -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="plantillaClave">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element ref="elementoDependiente"/>
        <xs:element ref="elementoIndependiente"/>
      </xs:choice>
    </xs:complexType>
    <xs:key name="relacion">
      <xs:selector xpath="elementoIndependiente"/>
      <xs:field xpath="@atributoIndependiente_esKey"/>
    </xs:key>
    <xs:keyref name="referenciaClave" refer="relacion">
      <xs:selector xpath="elementoDependiente"/>
      <xs:field xpath="@atributoDependiente_esKeyref"/>
    </xs:keyref>
  </xs:element>
  
  <xs:element name="elementoDependiente">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombreDependiente" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="atributoDependiente_esKeyref" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="elementoIndependiente">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombreIndependiente" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="atributoIndependiente_esKey" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== borjamiguens/DAWlenguajeDeMarcas/Evaluacion_1/Practicas/XML_XSD_actividades/plantillaClave/plantillaClave.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Plantilla para implementar claves -->
<plantillaClave xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
              xsi:noNamespaceSchemaLocation="plantillaClave.xsd">
  <elementoDependiente atributoDependiente_esKeyref="ES">
    <nombreDependiente>Madrid</nombreDependiente>
  </elementoDependiente>
  <elementoDependiente atributoDependiente_esKeyref="JP">
    <nombreDependiente>Tokio</nombreDependiente>
  </elementoDependiente>

  <elementoIndependiente atributoIndependiente_esKey="ES">
    <nombreIndependiente>España</nombreIndependiente>
  </elementoIndependiente>
  <elementoIndependiente atributoIndependiente_esKey="JP">
    <nombreIndependiente>Japón</nombreIndependiente>
  </elementoIndependiente>
  
<!-- el siguiente elementoIndependiente puede existir sin ser referenciado -->  
  <elementoIndependiente atributoIndependiente_esKey="PT">
    <nombreIndependiente>Portugal</nombreIndependiente>
  </elementoIndependiente>
 
</plantillaClave>
