<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<!DOCTYPE mensaxe [
<!ELEMENT mensaxe (de , para+ , asunto , corpo? , adxunto*)>
<!ATTLIST mensaxe prioridade (baixa | normal | urxente) #REQUIRED>
<!ATTLIST mensaxe gardarBandexa CDATA "Enviados">
<!ELEMENT de (#PCDATA)>
<!ELEMENT para (#PCDATA)>
<!ELEMENT asunto (#PCDATA)>
<!ELEMENT corpo (#PCDATA)>
<!ELEMENT adxunto (#PCDATA)>
]>
<mensaxe prioridade="baja">
   <de>maria@gmail.com</de>
   <para>ignacio@mail.com</para>
   <para>maria@mail.com</para>
    <asunto>Envíoche os arquivos</asunto>
     <corpo>te envío las fotos de la última semana</corpo>
   <adxunto>D:\fotos\naCea.jpg</adxunto>
   <adxunto>D:\fotos\naPraia.jpg</adxunto>
  <adxunto>D:\fotos\naCea.jpg</adxunto>
</mensaxe>
