=== borjamiguens/DAWlenguajeDeMarcas/Evaluacion_1/Practicas/XML_XSD_actividades/pag_23_unique.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="agenda">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="contacto" type="tipoContacto" maxOccurs="100"/>
      </xs:sequence>
    </xs:complexType>
    <xs:unique name="nomeUnico">
      <xs:selector xpath="contacto"/>
      <xs:field xpath="nome"/>
    </xs:unique>
  </xs:element>
  
  <xs:complexType name="tipoContacto">
    <xs:sequence>
      <xs:element name="nome" type="xs:string"/>
      <xs:element name="telefono" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== borjamiguens/DAWlenguajeDeMarcas/Evaluacion_1/Practicas/XML_XSD_actividades/pag_23_unique.xml
<?xml version="1.0" encoding="UTF-8"?>
<agenda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                  xsi:noNamespaceSchemaLocation="pag_23_unique.xsd">
  <contacto>
    <nome>Iria</nome>
    <telefono>988988988</telefono>
  </contacto>
  <contacto>
    <nome>Xoel</nome>
    <telefono>988988999</telefono>
  </contacto>
  <!-- ejemplar de prueba para no válido -->
  <contacto>
    <nome>Pedro</nome>
    <telefono>988988999</telefono>
  </contacto>
</agenda>
